/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const Cell = IDL.Record({
  'col' : IDL.Nat,
  'row' : IDL.Nat,
  'value' : IDL.Text,
  'timestamp' : IDL.Int,
  'editedBy' : IDL.Text,
  'formula' : IDL.Text,
});
export const Presence = IDL.Record({
  'userName' : IDL.Text,
  'color' : IDL.Text,
  'lastActive' : IDL.Int,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'lastModified' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkPermission' : IDL.Func([], [], []),
  'createDocument' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteDocument' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCells' : IDL.Func([IDL.Text], [IDL.Vec(Cell)], ['query']),
  'getPresence' : IDL.Func([IDL.Text], [IDL.Vec(Presence)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'heartbeat' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'leaveDocument' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'listDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCell' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'color' : IDL.Text });
  const Cell = IDL.Record({
    'col' : IDL.Nat,
    'row' : IDL.Nat,
    'value' : IDL.Text,
    'timestamp' : IDL.Int,
    'editedBy' : IDL.Text,
    'formula' : IDL.Text,
  });
  const Presence = IDL.Record({
    'userName' : IDL.Text,
    'color' : IDL.Text,
    'lastActive' : IDL.Int,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'lastModified' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkPermission' : IDL.Func([], [], []),
    'createDocument' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteDocument' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCells' : IDL.Func([IDL.Text], [IDL.Vec(Cell)], ['query']),
    'getPresence' : IDL.Func([IDL.Text], [IDL.Vec(Presence)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'heartbeat' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'leaveDocument' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'listDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCell' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };