/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell {
  'col' : bigint,
  'row' : bigint,
  'value' : string,
  'timestamp' : bigint,
  'editedBy' : string,
  'formula' : string,
}
export interface Document {
  'id' : string,
  'title' : string,
  'authorName' : string,
  'author' : Principal,
  'lastModified' : bigint,
}
export interface Presence {
  'userName' : string,
  'color' : string,
  'lastActive' : bigint,
}
export interface UserProfile { 'name' : string, 'color' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkPermission' : ActorMethod<[], undefined>,
  'createDocument' : ActorMethod<[string], string>,
  'deleteDocument' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCells' : ActorMethod<[string], Array<Cell>>,
  'getPresence' : ActorMethod<[string], Array<Presence>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'heartbeat' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinDocument' : ActorMethod<[string, string, string], string>,
  'leaveDocument' : ActorMethod<[string, string], undefined>,
  'listDocuments' : ActorMethod<[], Array<Document>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCell' : ActorMethod<
    [string, bigint, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];